# IDCI Metadata
idci_simple_metadata:
    namespaces: [tags]


# FOS Elastica
fos_elastica:
    clients:
        default:
          host: "%elasticsearch_host%"
          port: "%elasticsearch_port%"
    indexes:
        tms_faq:
            types:
                question:
                    properties:
                        faqId:        ~
                        categoriesId: ~
                        tagsValue:    { type: text, boost: 5 }
                        question:     { type: text, boost: 3 }
                        answer:       { type: text, boost: 1 }
                    persistence:
                        # the driver can be orm, mongodb or propel
                        driver: orm
                        model: Tms\Bundle\FaqBundle\Entity\Question
                        provider: ~
                        # listener and finder are not supported by
                        # propel and should be removed
                        listener: ~
                        finder: ~
# Model IO
tms_model_io:
    models:
    ## Common
        metadatas:
            object_manager: doctrine
            class: IDCI\Bundle\SimpleMetadataBundle\Entity\Metadata
            aliases: ["tags"]
            modes:
                simple:
                    - namespace
                    - key
                    - value
                    - objectClassName
        images:
            object_manager: doctrine
            class: Tms\Bundle\MediaClientBundle\Entity\Media
            aliases: ["icon"]
            modes:
                simple:
                    - publicUri
                    - mimeType
                    - providerName
                    - providerReference
                    - providerData
                    - extension
                    - metadata
    ## Faq
        faq:
            object_manager: doctrine
            class: Tms\Bundle\FaqBundle\Entity\Faq
            aliases: ["faq"]
            modes:
                full:
                    - title
                    - enabled
                    - hash
                    - objectClassName
                    - objectId
                    - questions: {mode: full}
                    - categories: {mode: full}
        question:
            object_manager: doctrine
            class: Tms\Bundle\FaqBundle\Entity\Question
            aliases: ["questions"]
            modes:
                full:
                    - question
                    - answer
                    - average
                    - countYep
                    - countNope
                    - tags: {mode: simple}
                    - categories: {mode: full}
        question_categories:
            object_manager: doctrine
            class: Tms\Bundle\FaqBundle\Entity\QuestionCategory
            aliases: ["categories"]
            modes:
                full:
                    - name
                    - slug
                    - icon: {mode: simple}
                    - countYep
                    - countNope
                    - tags: {mode: simple}
