# IDCI exporter
idci_exporter:
    entities:
        faqs:
            class: "Tms\\Bundle\\FaqBundle\\Entity\\Faq"
        evaluations:
            class: "Tms\\Bundle\\FaqBundle\\Entity\\Evaluation"
        consumerSearchs:
            class: "Tms\\Bundle\\FaqBundle\\Entity\\ConsumerSearch"
