# IDCI Metadata
idci_simple_metadata:
    namespaces: [tags]


# FOS Elastica
fos_elastica:
    clients:
        default:
          host: %elasticsearch_host%
          port: %elasticsearch_port%
    indexes:
        tms_faq:
            types:
                question:
                    mappings:
                        faqId:        ~
                        categoriesId: ~
                        tagsValue:    { boost: 5 }
                        question:     { boost: 3 }
                        answer:       { boost: 1 }
                    persistence:
                        # the driver can be orm, mongodb or propel
                        driver: orm
                        model: Tms\Bundle\FaqBundle\Entity\Question
                        provider: ~
                        # listener and finder are not supported by
                        # propel and should be removed
                        listener:
                            immediate: ~
                        finder: ~
