# IDCI exporter
idci_exporter:
    entities:
        faqs:
            class: "Tms\\Bundle\\FaqBundle\\Entity\\Faq"
        evaluations:
            class: "Tms\\Bundle\\FaqBundle\\Entity\\Evaluation"
        consumerSearchs:
            class: "Tms\\Bundle\\FaqBundle\\Entity\\ConsumerSearch"
        questions:
            class: "Tms\\Bundle\\FaqBundle\\Entity\\Question"
        responses:
            class: "Tms\\Bundle\\FaqBundle\\Entity\\Response"

# IDCI Metadata
idci_simple_metadata:
    namespaces: [tags]
