# IDCI Metadata
idci_simple_metadata:
    namespaces: [tags]

# Search
tms_search:
    indexes:
        tms_faq_question:
            class: Tms\Bundle\FaqBundle\Entity\Question
            indexer:
                service_name: tms_search.indexer.elasticsearch
                options:
                    host: %tms_search_host%
                    port: %tms_search_port%
                    collection_name: tms_faq_question