services:
    tms_faq.manager.faq:
        class: Tms\Bundle\FaqBundle\Manager\FaqManager
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher]
    tms_faq.manager.faq_question:
        class: Tms\Bundle\FaqBundle\Manager\FaqQuestionManager
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher]
    tms_faq.manager.faq_question_category:
        class: Tms\Bundle\FaqBundle\Manager\FaqQuestionCategoryManager
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher]
    tms_faq.manager.faq_response:
        class: Tms\Bundle\FaqBundle\Manager\FaqResponseManager
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher]
