Tms\Bundle\FaqBundle\Entity\QuestionCategory:
    exclusion_policy: ALL

    properties:
        id:
            expose: true
            groups: [tms_rest.collection, tms_rest.item]

        name:
            expose: true
            groups: [tms_rest.collection, tms_rest.item]

        slug:
            expose: true
            groups: [tms_rest.collection, tms_rest.item]

        questions:
            expose: true
            groups: [tms_rest.item]

    virtual_properties:
        getTags:
            groups: [tms_rest.collection, tms_rest.item]
            serialized_name: tags
