Tms\Bundle\FaqBundle\Entity\Evaluation:
    exclusion_policy: ALL

    properties:
        id:
            expose: true
            groups: [tms_rest.collection, tms_rest.item, tms_modelio]

        value:
            expose: true
            groups: [tms_rest.collection, tms_rest.item, tms_modelio]

        createdAt:
            expose: true
            groups: [tms_rest.collection, tms_rest.item, tms_modelio]
            serialized_name: createdAt