Tms\Bundle\FaqBundle\Entity\QuestionCategory:
    exclusion_policy: ALL

    properties:
        id:
            expose: true
            groups: [tms_rest.collection, tms_rest.item, tms_modelio]

        name:
            expose: true
            groups: [tms_rest.collection, tms_rest.item, tms_modelio]

        slug:
            expose: true
            groups: [tms_rest.collection, tms_rest.item, tms_modelio]

        icon:
            expose: true
            groups: [tms_rest.item, tms_modelio]

    virtual_properties:
        getTags:
            groups: [tms_rest.collection, tms_rest.item]
            serialized_name: tags